import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1786731893947 implements MigrationInterface {
    name = 'InitialSchema1786731893947'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."missing_person_reports_documenttype_enum" AS ENUM('CC', 'TI', 'RC', 'CE', 'PASAPORTE', 'PEP', 'NINGUNO')`);
        await queryRunner.query(`CREATE TYPE "public"."missing_person_reports_sex_enum" AS ENUM('MALE', 'FEMALE', 'OTHER', 'UNKNOWN')`);
        await queryRunner.query(`CREATE TYPE "public"."missing_person_reports_reporterrole_enum" AS ENUM('CITIZEN', 'FAMILY', 'RESCUER', 'HEALTH_STAFF', 'OFFICIAL', 'VOLUNTEER')`);
        await queryRunner.query(`CREATE TYPE "public"."missing_person_reports_status_enum" AS ENUM('ACTIVE', 'MATCHED', 'FOUND_ALIVE', 'FOUND_DECEASED', 'DUPLICATE', 'CANCELLED')`);
        await queryRunner.query(`CREATE TYPE "public"."missing_person_reports_source_enum" AS ENUM('APP', 'UNGRD', 'CRUZ_ROJA', 'DEFENSA_CIVIL', 'BOMBEROS', 'FISCALIA', 'IMPORT')`);
        await queryRunner.query(`CREATE TABLE "missing_person_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clientUuid" uuid NOT NULL, "revision" bigint NOT NULL DEFAULT '0', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "fullName" character varying(200) NOT NULL, "aliases" text array NOT NULL DEFAULT '{}', "documentType" "public"."missing_person_reports_documenttype_enum" NOT NULL DEFAULT 'NINGUNO', "documentNumber" text, "documentHash" character(64), "age" integer, "ageMin" integer, "ageMax" integer, "sex" "public"."missing_person_reports_sex_enum" NOT NULL DEFAULT 'UNKNOWN', "heightCm" integer, "build" character varying(120), "skinTone" character varying(120), "hairColor" character varying(120), "clothingDescription" text, "distinguishingMarks" text, "medicalNotes" text, "isMinor" boolean NOT NULL DEFAULT false, "lastSeenLocation" geography(Point,4326), "lastSeenAddress" text, "department" character varying(100), "municipality" character varying(120), "lastSeenAt" TIMESTAMP WITH TIME ZONE, "circumstances" text, "reporterName" character varying(200) NOT NULL, "reporterPhone" text, "reporterPhoneHash" character(64), "reporterEmail" text, "reporterRelationship" character varying(120), "reporterRole" "public"."missing_person_reports_reporterrole_enum" NOT NULL DEFAULT 'FAMILY', "claimTokenHash" character(64) NOT NULL, "status" "public"."missing_person_reports_status_enum" NOT NULL DEFAULT 'ACTIVE', "source" "public"."missing_person_reports_source_enum" NOT NULL DEFAULT 'APP', "externalReference" character varying(120), "mergedIntoId" uuid, "resolutionNotes" text, "resolvedAt" TIMESTAMP WITH TIME ZONE, "consentPublicListing" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_2e6cc5d76bc37811f5ea093e8b0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8c3ac168d13667c1bdd0e71767" ON "missing_person_reports" ("clientUuid") `);
        await queryRunner.query(`CREATE INDEX "IDX_5fbc44b8000acd855fd6e4f4d0" ON "missing_person_reports" ("revision") `);
        await queryRunner.query(`CREATE INDEX "IDX_4475dc5dd23d7e428ba1ac1ca4" ON "missing_person_reports" ("fullName") `);
        await queryRunner.query(`CREATE INDEX "IDX_782855816a0bda4bd557610765" ON "missing_person_reports" ("documentHash") `);
        await queryRunner.query(`CREATE INDEX "IDX_639120bb75d937412c90bde5d4" ON "missing_person_reports" USING GiST ("lastSeenLocation") `);
        await queryRunner.query(`CREATE INDEX "IDX_71b9a1df5c4df32bcfc4cf3be1" ON "missing_person_reports" ("department") `);
        await queryRunner.query(`CREATE INDEX "IDX_defe29eed8a18ed921b1587a31" ON "missing_person_reports" ("lastSeenAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_e2edb69742a532ed1285db966a" ON "missing_person_reports" ("reporterPhoneHash") `);
        await queryRunner.query(`CREATE INDEX "IDX_71b9d1a0cf522801c3ba495d84" ON "missing_person_reports" ("claimTokenHash") `);
        await queryRunner.query(`CREATE INDEX "IDX_cd90821f2c20e7b9584c6cc6d6" ON "missing_person_reports" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_95ec4fa7a2b50ca91d52c5354a" ON "missing_person_reports" ("status", "department") `);
        await queryRunner.query(`CREATE TYPE "public"."person_photos_ownertype_enum" AS ENUM('MISSING_REPORT', 'SIGHTING_REPORT')`);
        await queryRunner.query(`CREATE TABLE "person_photos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clientUuid" uuid NOT NULL, "ownerType" "public"."person_photos_ownertype_enum" NOT NULL, "missingReportId" uuid, "sightingReportId" uuid, "storageKey" character varying(500) NOT NULL, "mimeType" character varying(100) NOT NULL, "sizeBytes" integer NOT NULL, "width" integer, "height" integer, "perceptualHash" character varying(64), "faceDescriptor" jsonb, "hasFace" boolean, "processedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5a62ba75233ae0dd6c9dee6d306" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a59476668b5733266a40c4eee6" ON "person_photos" ("clientUuid") `);
        await queryRunner.query(`CREATE INDEX "IDX_bb31425878fc7e5636f040dcb7" ON "person_photos" ("perceptualHash") `);
        await queryRunner.query(`CREATE INDEX "IDX_0028462ad27b78f64fdae0f345" ON "person_photos" ("ownerType", "sightingReportId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ed20c7cab16327f0dd0e17e7ac" ON "person_photos" ("ownerType", "missingReportId") `);
        await queryRunner.query(`CREATE TYPE "public"."sighting_reports_kind_enum" AS ENUM('SIGHTING', 'SHELTER_INTAKE', 'HOSPITAL_ADMISSION', 'RESCUE', 'MORGUE', 'SELF_REPORT')`);
        await queryRunner.query(`CREATE TYPE "public"."sighting_reports_documenttype_enum" AS ENUM('CC', 'TI', 'RC', 'CE', 'PASAPORTE', 'PEP', 'NINGUNO')`);
        await queryRunner.query(`CREATE TYPE "public"."sighting_reports_sex_enum" AS ENUM('MALE', 'FEMALE', 'OTHER', 'UNKNOWN')`);
        await queryRunner.query(`CREATE TYPE "public"."sighting_reports_condition_enum" AS ENUM('STABLE', 'INJURED', 'CRITICAL', 'DECEASED', 'UNKNOWN')`);
        await queryRunner.query(`CREATE TYPE "public"."sighting_reports_reporterrole_enum" AS ENUM('CITIZEN', 'FAMILY', 'RESCUER', 'HEALTH_STAFF', 'OFFICIAL', 'VOLUNTEER')`);
        await queryRunner.query(`CREATE TYPE "public"."sighting_reports_source_enum" AS ENUM('APP', 'UNGRD', 'CRUZ_ROJA', 'DEFENSA_CIVIL', 'BOMBEROS', 'FISCALIA', 'IMPORT')`);
        await queryRunner.query(`CREATE TABLE "sighting_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clientUuid" uuid NOT NULL, "revision" bigint NOT NULL DEFAULT '0', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "kind" "public"."sighting_reports_kind_enum" NOT NULL DEFAULT 'SIGHTING', "fullName" character varying(200), "documentType" "public"."sighting_reports_documenttype_enum" NOT NULL DEFAULT 'NINGUNO', "documentNumber" text, "documentHash" character(64), "estimatedAgeMin" integer, "estimatedAgeMax" integer, "sex" "public"."sighting_reports_sex_enum" NOT NULL DEFAULT 'UNKNOWN', "heightCm" integer, "build" character varying(120), "skinTone" character varying(120), "hairColor" character varying(120), "clothingDescription" text, "distinguishingMarks" text, "condition" "public"."sighting_reports_condition_enum" NOT NULL DEFAULT 'UNKNOWN', "isMinor" boolean NOT NULL DEFAULT false, "location" geography(Point,4326), "address" text, "department" character varying(100), "municipality" character varying(120), "facilityName" character varying(200), "seenAt" TIMESTAMP WITH TIME ZONE NOT NULL, "notes" text, "reporterName" character varying(200), "reporterPhone" text, "reporterRole" "public"."sighting_reports_reporterrole_enum" NOT NULL DEFAULT 'CITIZEN', "reporterOrganization" character varying(200), "claimTokenHash" character(64), "source" "public"."sighting_reports_source_enum" NOT NULL DEFAULT 'APP', "status" character varying(32) NOT NULL DEFAULT 'OPEN', "matchedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_72a4dc4461b84dd0b72b1390bc4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0bf557b021ba490cf0cdbb75c2" ON "sighting_reports" ("clientUuid") `);
        await queryRunner.query(`CREATE INDEX "IDX_9e53f501f39abe96ef3934ffdc" ON "sighting_reports" ("revision") `);
        await queryRunner.query(`CREATE INDEX "IDX_38907fb600f01b39cb478dba8b" ON "sighting_reports" ("fullName") `);
        await queryRunner.query(`CREATE INDEX "IDX_36736f128f4effa80efeb9c36a" ON "sighting_reports" ("documentHash") `);
        await queryRunner.query(`CREATE INDEX "IDX_0539ca7e2c86e1260a4519d51f" ON "sighting_reports" USING GiST ("location") `);
        await queryRunner.query(`CREATE INDEX "IDX_56bcc51ba2a1e7497ac7d93945" ON "sighting_reports" ("department") `);
        await queryRunner.query(`CREATE INDEX "IDX_c4c7ab45116801aa01197e2b2a" ON "sighting_reports" ("seenAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_53c5da1062ecddea8e1c31b379" ON "sighting_reports" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_e0abb73a8d1e873638752c3f3a" ON "sighting_reports" ("status", "department") `);
        await queryRunner.query(`CREATE TYPE "public"."match_candidates_tier_enum" AS ENUM('DETERMINISTIC', 'BIOMETRIC', 'HEURISTIC')`);
        await queryRunner.query(`CREATE TYPE "public"."match_candidates_status_enum" AS ENUM('PENDING_REVIEW', 'CONFIRMED', 'REJECTED', 'SUPERSEDED')`);
        await queryRunner.query(`CREATE TABLE "match_candidates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "missingReportId" uuid NOT NULL, "sightingReportId" uuid NOT NULL, "score" double precision NOT NULL, "tier" "public"."match_candidates_tier_enum" NOT NULL, "breakdown" jsonb NOT NULL, "status" "public"."match_candidates_status_enum" NOT NULL DEFAULT 'PENDING_REVIEW', "highPriority" boolean NOT NULL DEFAULT false, "reviewedById" uuid, "reviewedByName" character varying(200), "reviewedAt" TIMESTAMP WITH TIME ZONE, "reviewNotes" text, "notifiedAt" TIMESTAMP WITH TIME ZONE, "engineVersion" character varying(20) NOT NULL DEFAULT 'v1', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_match_pair" UNIQUE ("missingReportId", "sightingReportId"), CONSTRAINT "PK_6ff6206a91e00ded958f53a9839" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_26f6e6f1f5e3df0314b1a840b7" ON "match_candidates" ("missingReportId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9713dfc7a4ad4dba500a4e4ee4" ON "match_candidates" ("sightingReportId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bbabf49897a1283005687bc3db" ON "match_candidates" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_4f0a67d672f09f9d4638a36f7d" ON "match_candidates" ("status", "score") `);
        await queryRunner.query(`CREATE TYPE "public"."notification_outbox_kind_enum" AS ENUM('MATCH_CONFIRMED', 'MATCH_PENDING_REVIEW', 'MATCH_REJECTED', 'REPORT_RECEIVED', 'ZONE_NEARBY_ALERT')`);
        await queryRunner.query(`CREATE TYPE "public"."notification_outbox_channel_enum" AS ENUM('WEBSOCKET', 'PUSH', 'SMS', 'EMAIL')`);
        await queryRunner.query(`CREATE TYPE "public"."notification_outbox_status_enum" AS ENUM('PENDING', 'SENT', 'FAILED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "notification_outbox" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "kind" "public"."notification_outbox_kind_enum" NOT NULL, "channel" "public"."notification_outbox_channel_enum" NOT NULL, "recipientKey" character varying(128) NOT NULL, "recipientAddress" text, "title" character varying(200) NOT NULL, "body" text NOT NULL, "payload" jsonb NOT NULL DEFAULT '{}', "status" "public"."notification_outbox_status_enum" NOT NULL DEFAULT 'PENDING', "attempts" integer NOT NULL DEFAULT '0', "nextAttemptAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "sentAt" TIMESTAMP WITH TIME ZONE, "lastError" text, "relatedEntityId" uuid, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_83d47c7dba1da2d038749fe757e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3af8906b2c1e0e48cb7ecadbed" ON "notification_outbox" ("recipientKey") `);
        await queryRunner.query(`CREATE INDEX "IDX_ae04faa3dd7b52557a4c798c6b" ON "notification_outbox" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_a1ae5413f0c15b23a392ea8f97" ON "notification_outbox" ("status", "nextAttemptAt") `);
        await queryRunner.query(`CREATE TABLE "devices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deviceId" character varying(64) NOT NULL, "platform" character varying(20) NOT NULL, "pushToken" text, "claimTokenHashes" text array NOT NULL DEFAULT '{}', "locale" character varying(10) NOT NULL DEFAULT 'es', "lastSeenAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b1514758245c12daf43486dd1f0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_666c9b59efda8ca85b29157152" ON "devices" ("deviceId") `);
        await queryRunner.query(`CREATE TYPE "public"."zone_report_votes_vote_enum" AS ENUM('CONFIRM', 'REFUTE')`);
        await queryRunner.query(`CREATE TYPE "public"."zone_report_votes_voterrole_enum" AS ENUM('CITIZEN', 'FAMILY', 'RESCUER', 'HEALTH_STAFF', 'OFFICIAL', 'VOLUNTEER')`);
        await queryRunner.query(`CREATE TABLE "zone_report_votes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clientUuid" uuid NOT NULL, "zoneReportId" uuid NOT NULL, "vote" "public"."zone_report_votes_vote_enum" NOT NULL, "deviceId" character varying(64) NOT NULL, "voterRole" "public"."zone_report_votes_voterrole_enum" NOT NULL DEFAULT 'CITIZEN', "location" geography(Point,4326), "distanceMeters" integer, "comment" text, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_vote_per_device" UNIQUE ("zoneReportId", "deviceId"), CONSTRAINT "PK_ea9c8b4c1a968c46c88c7bc00ed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3fe3b314b07a63351c96e42851" ON "zone_report_votes" ("clientUuid") `);
        await queryRunner.query(`CREATE INDEX "IDX_dc0e2096713bc79ee6d252a377" ON "zone_report_votes" ("zoneReportId") `);
        await queryRunner.query(`CREATE TYPE "public"."zone_reports_type_enum" AS ENUM('ROAD_BLOCKED', 'ROAD_PARTIAL', 'ROAD_PASSABLE', 'ROAD_4X4_ONLY', 'BRIDGE_DOWN', 'LANDSLIDE', 'COLLAPSED_BUILDING', 'UNSTABLE_STRUCTURE', 'FIRE', 'GAS_LEAK', 'FLOOD', 'AFTERSHOCK_DAMAGE', 'SHELTER', 'MEDICAL_POST', 'SUPPLY_POINT', 'WATER_POINT', 'HELICOPTER_LZ', 'FUEL', 'ACTIVE_RESCUE', 'PEOPLE_TRAPPED', 'NO_SIGNAL', 'POWER_OUTAGE', 'NO_WATER')`);
        await queryRunner.query(`CREATE TYPE "public"."zone_reports_reporterrole_enum" AS ENUM('CITIZEN', 'FAMILY', 'RESCUER', 'HEALTH_STAFF', 'OFFICIAL', 'VOLUNTEER')`);
        await queryRunner.query(`CREATE TYPE "public"."zone_reports_status_enum" AS ENUM('ACTIVE', 'RESOLVED', 'EXPIRED', 'MODERATED_OUT')`);
        await queryRunner.query(`CREATE TABLE "zone_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clientUuid" uuid NOT NULL, "revision" bigint NOT NULL DEFAULT '0', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "type" "public"."zone_reports_type_enum" NOT NULL, "location" geography(Point,4326) NOT NULL, "path" geography(LineString,4326), "radiusMeters" integer, "description" text, "roadName" character varying(200), "department" character varying(100), "municipality" character varying(120), "severity" integer NOT NULL DEFAULT '3', "reportedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "halfLifeMinutes" integer NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE, "baseConfidence" double precision NOT NULL DEFAULT '0.4', "confirmations" integer NOT NULL DEFAULT '0', "refutations" integer NOT NULL DEFAULT '0', "lastConfirmedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "reporterRole" "public"."zone_reports_reporterrole_enum" NOT NULL DEFAULT 'CITIZEN', "reporterOrganization" character varying(200), "deviceId" character varying(64) NOT NULL, "status" "public"."zone_reports_status_enum" NOT NULL DEFAULT 'ACTIVE', "resolutionNotes" text, "photoStorageKey" character varying(500), CONSTRAINT "PK_8a95677e50b1df637bc78175a15" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d561b63e090b9e352ac56810a0" ON "zone_reports" ("clientUuid") `);
        await queryRunner.query(`CREATE INDEX "IDX_e655eda0d3bb0164a6c56912d8" ON "zone_reports" ("revision") `);
        await queryRunner.query(`CREATE INDEX "IDX_09c0dd3d11216302d8392c8ed2" ON "zone_reports" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_a0e3795a55a1218177530cb01e" ON "zone_reports" USING GiST ("location") `);
        await queryRunner.query(`CREATE INDEX "IDX_05797a7a01b12ec3edd29f42f4" ON "zone_reports" USING GiST ("path") `);
        await queryRunner.query(`CREATE INDEX "IDX_07987176e0e6e536cb8e5fe1fd" ON "zone_reports" ("department") `);
        await queryRunner.query(`CREATE INDEX "IDX_7f10da07014eaee55d7b2b4174" ON "zone_reports" ("reportedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_5183aae24a43a1577737536a91" ON "zone_reports" ("deviceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e17053cb2c0f7730840d0b4de0" ON "zone_reports" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c703ad94e747499e9df5708316" ON "zone_reports" ("status", "reportedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_2e21f268f9d6c0d162b255f38d" ON "zone_reports" ("status", "type") `);
        await queryRunner.query(`CREATE TYPE "public"."operators_role_enum" AS ENUM('VALIDATOR', 'COORDINATOR', 'ADMIN', 'VIEWER')`);
        await queryRunner.query(`CREATE TABLE "operators" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(200) NOT NULL, "fullName" character varying(200) NOT NULL, "organization" character varying(200), "passwordHash" character varying(255) NOT NULL, "role" "public"."operators_role_enum" NOT NULL DEFAULT 'VALIDATOR', "isActive" boolean NOT NULL DEFAULT true, "lastLoginAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_3d02b3692836893720335a79d1b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1570f3d85c3ff08bb99815897a" ON "operators" ("email") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "actorId" uuid, "actorName" character varying(200), "action" character varying(60) NOT NULL, "entityType" character varying(60) NOT NULL, "entityId" uuid, "metadata" jsonb NOT NULL DEFAULT '{}', "ipAddress" character varying(60), "userAgent" character varying(300), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_678217ebecd415a0db47435d15" ON "audit_logs" ("actorId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_13c69424c440a0e765053feb4b" ON "audit_logs" ("entityType", "entityId") `);
        await queryRunner.query(`ALTER TABLE "person_photos" ADD CONSTRAINT "FK_f679dfc8cfa8814c62603b05090" FOREIGN KEY ("missingReportId") REFERENCES "missing_person_reports"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "person_photos" ADD CONSTRAINT "FK_dcf5388b0a858c2ed1b6817aa37" FOREIGN KEY ("sightingReportId") REFERENCES "sighting_reports"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_candidates" ADD CONSTRAINT "FK_26f6e6f1f5e3df0314b1a840b7d" FOREIGN KEY ("missingReportId") REFERENCES "missing_person_reports"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_candidates" ADD CONSTRAINT "FK_9713dfc7a4ad4dba500a4e4ee4c" FOREIGN KEY ("sightingReportId") REFERENCES "sighting_reports"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "zone_report_votes" ADD CONSTRAINT "FK_dc0e2096713bc79ee6d252a377d" FOREIGN KEY ("zoneReportId") REFERENCES "zone_reports"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "zone_report_votes" DROP CONSTRAINT "FK_dc0e2096713bc79ee6d252a377d"`);
        await queryRunner.query(`ALTER TABLE "match_candidates" DROP CONSTRAINT "FK_9713dfc7a4ad4dba500a4e4ee4c"`);
        await queryRunner.query(`ALTER TABLE "match_candidates" DROP CONSTRAINT "FK_26f6e6f1f5e3df0314b1a840b7d"`);
        await queryRunner.query(`ALTER TABLE "person_photos" DROP CONSTRAINT "FK_dcf5388b0a858c2ed1b6817aa37"`);
        await queryRunner.query(`ALTER TABLE "person_photos" DROP CONSTRAINT "FK_f679dfc8cfa8814c62603b05090"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13c69424c440a0e765053feb4b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_678217ebecd415a0db47435d15"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1570f3d85c3ff08bb99815897a"`);
        await queryRunner.query(`DROP TABLE "operators"`);
        await queryRunner.query(`DROP TYPE "public"."operators_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e21f268f9d6c0d162b255f38d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c703ad94e747499e9df5708316"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e17053cb2c0f7730840d0b4de0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5183aae24a43a1577737536a91"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f10da07014eaee55d7b2b4174"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_07987176e0e6e536cb8e5fe1fd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_05797a7a01b12ec3edd29f42f4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a0e3795a55a1218177530cb01e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_09c0dd3d11216302d8392c8ed2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e655eda0d3bb0164a6c56912d8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d561b63e090b9e352ac56810a0"`);
        await queryRunner.query(`DROP TABLE "zone_reports"`);
        await queryRunner.query(`DROP TYPE "public"."zone_reports_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."zone_reports_reporterrole_enum"`);
        await queryRunner.query(`DROP TYPE "public"."zone_reports_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc0e2096713bc79ee6d252a377"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3fe3b314b07a63351c96e42851"`);
        await queryRunner.query(`DROP TABLE "zone_report_votes"`);
        await queryRunner.query(`DROP TYPE "public"."zone_report_votes_voterrole_enum"`);
        await queryRunner.query(`DROP TYPE "public"."zone_report_votes_vote_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_666c9b59efda8ca85b29157152"`);
        await queryRunner.query(`DROP TABLE "devices"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a1ae5413f0c15b23a392ea8f97"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae04faa3dd7b52557a4c798c6b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3af8906b2c1e0e48cb7ecadbed"`);
        await queryRunner.query(`DROP TABLE "notification_outbox"`);
        await queryRunner.query(`DROP TYPE "public"."notification_outbox_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notification_outbox_channel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notification_outbox_kind_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4f0a67d672f09f9d4638a36f7d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bbabf49897a1283005687bc3db"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9713dfc7a4ad4dba500a4e4ee4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26f6e6f1f5e3df0314b1a840b7"`);
        await queryRunner.query(`DROP TABLE "match_candidates"`);
        await queryRunner.query(`DROP TYPE "public"."match_candidates_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."match_candidates_tier_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e0abb73a8d1e873638752c3f3a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_53c5da1062ecddea8e1c31b379"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c4c7ab45116801aa01197e2b2a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_56bcc51ba2a1e7497ac7d93945"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0539ca7e2c86e1260a4519d51f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_36736f128f4effa80efeb9c36a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_38907fb600f01b39cb478dba8b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9e53f501f39abe96ef3934ffdc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0bf557b021ba490cf0cdbb75c2"`);
        await queryRunner.query(`DROP TABLE "sighting_reports"`);
        await queryRunner.query(`DROP TYPE "public"."sighting_reports_source_enum"`);
        await queryRunner.query(`DROP TYPE "public"."sighting_reports_reporterrole_enum"`);
        await queryRunner.query(`DROP TYPE "public"."sighting_reports_condition_enum"`);
        await queryRunner.query(`DROP TYPE "public"."sighting_reports_sex_enum"`);
        await queryRunner.query(`DROP TYPE "public"."sighting_reports_documenttype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."sighting_reports_kind_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed20c7cab16327f0dd0e17e7ac"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0028462ad27b78f64fdae0f345"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bb31425878fc7e5636f040dcb7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a59476668b5733266a40c4eee6"`);
        await queryRunner.query(`DROP TABLE "person_photos"`);
        await queryRunner.query(`DROP TYPE "public"."person_photos_ownertype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_95ec4fa7a2b50ca91d52c5354a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cd90821f2c20e7b9584c6cc6d6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_71b9d1a0cf522801c3ba495d84"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e2edb69742a532ed1285db966a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_defe29eed8a18ed921b1587a31"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_71b9a1df5c4df32bcfc4cf3be1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_639120bb75d937412c90bde5d4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_782855816a0bda4bd557610765"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4475dc5dd23d7e428ba1ac1ca4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5fbc44b8000acd855fd6e4f4d0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c3ac168d13667c1bdd0e71767"`);
        await queryRunner.query(`DROP TABLE "missing_person_reports"`);
        await queryRunner.query(`DROP TYPE "public"."missing_person_reports_source_enum"`);
        await queryRunner.query(`DROP TYPE "public"."missing_person_reports_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."missing_person_reports_reporterrole_enum"`);
        await queryRunner.query(`DROP TYPE "public"."missing_person_reports_sex_enum"`);
        await queryRunner.query(`DROP TYPE "public"."missing_person_reports_documenttype_enum"`);
    }

}
